# Tutorial 8 Python Numpy Arrays

## Numpy Tutorials
#### Numpy is a general-purpose array-processing package. it provides a high-performance multidimensional array object, and tools for working with these arrays. it is the fundamental package for scientific computing wwith Python

# What is an Array?

#### An array is a data structure that stores values of same data type. In python this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, Arrays in python can only contain values corresponding to same data type.

In [1]:
import numpy as np

In [2]:
lst= [1,2,3,4]
arr=np.array(lst)

In [3]:
type(arr)

numpy.ndarray

In [4]:
lst1=[1,2,3,4,5]
lst2=[2,3,4,5,6]
lst3=[3,4,5,6,7]

arr1=np.array([lst1,lst2,lst3])

In [5]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [6]:
arr1.shape

(3, 5)

In [7]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [8]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [9]:
arr

array([1, 2, 3, 4])

In [10]:
arr[1]

2

In [11]:
arr[3]

4

In [12]:
arr[2]

3

In [13]:
len(arr)

4

In [14]:
arr[2]=6

In [15]:
arr

array([1, 2, 6, 4])

In [16]:
arr[:3]

array([1, 2, 6])

In [17]:
arr[:-1]

array([1, 2, 6])

In [18]:
arr[-1]

4

In [19]:
arr[:-1]

array([1, 2, 6])

In [20]:
arr[::-1]

array([4, 6, 2, 1])

In [21]:
arr[::-1]

array([4, 6, 2, 1])

In [22]:
arr[::-2]

array([4, 2])

In [23]:
arr[::-3]

array([4, 1])

In [24]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [25]:
arr1[:,1]

array([2, 3, 4])

In [26]:
arr1[1:,1:3]

array([[3, 4],
       [4, 5]])

In [27]:
arr1[0:,0:3]

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [28]:
arr1[0:,0:3]

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [29]:
arr1[1:,3:]

array([[5, 6],
       [6, 7]])

In [30]:
arr1[:,3:].shape

(3, 2)

In [31]:
arr1[:,[0,3]]

array([[1, 4],
       [2, 5],
       [3, 6]])

## EDA

In [33]:
arr

array([1, 2, 6, 4])

In [34]:
arr<2

array([ True, False, False, False])

In [35]:
arr[arr<2]

array([1])

In [36]:
arr1.shape

(3, 5)

In [37]:
arr1.shape

(3, 5)

In [38]:
arr1.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 3, 4],
       [5, 6, 7]])

## Mechanism to create an array

In [39]:
np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
np.arange(1,20,2).reshape(2,5)


array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [41]:
arr*arr

array([ 1,  4, 36, 16])

In [42]:
arr1*2

array([[ 2,  4,  6,  8, 10],
       [ 4,  6,  8, 10, 12],
       [ 6,  8, 10, 12, 14]])

In [43]:
arr1*arr1

array([[ 1,  4,  9, 16, 25],
       [ 4,  9, 16, 25, 36],
       [ 9, 16, 25, 36, 49]])

In [44]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [45]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Random Number

In [46]:
np.random.randint(10,50,8).reshape(2,4)

array([[44, 42, 46, 17],
       [30, 29, 15, 17]])